name: e2e tests on playwright
on:
  push:
    branches: ['dpavliuk/pom']
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependecies
      run: npm ci
    - name: Browser Chromium
      run: npx playwright install chromium --with-deps
    - name: Run playwright test
      run: npx playwright test guru.spec.js --project chromium --update-snapshots
    - name: Archiving the html report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5